version: "3.8"
services:
  csharp-calls-to-lua:
    build:
      context: .
      dockerfile: Dockerfile
    image: 2kcarlos/csharp-calls-to-lua
    container_name: csharp-calls-to-lua
    volumes:
      - type: bind
        source: ./docker-shared
        target: /docker-shared
